# Generated by Django 4.2.1 on 2024-03-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_amateurmatch_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amateurmatch',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
