# Generated by Django 4.2.1 on 2024-04-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_amateurmatch_lat_alter_amateurmatch_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='sports_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(upload_to='sports_images/', verbose_name='Изображение'),
        ),
    ]
