# Generated by Django 4.2.1 on 2024-04-01 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sport_icon_alter_sport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amateurmatch',
            name='opponent',
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='auto_accept_participants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='max_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='participants',
            field=models.ManyToManyField(related_name='opponents_amateur_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='requests',
            field=models.ManyToManyField(related_name='requests_amateur_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_avatars/', verbose_name='Аватары'),
        ),
    ]
