# Generated by Django 4.2.1 on 2024-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_amateurmatch_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amateurmatch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='amateur_matches_photos/'),
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Запланирован'), (1, 'В процессе'), (2, 'Завершен'), (3, 'Отменен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='auto_accept_participants',
            field=models.BooleanField(default=False, verbose_name='Автоматически принимать всех'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='enter_price',
            field=models.IntegerField(verbose_name='Цена входа'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='max_participants',
            field=models.IntegerField(default=1, verbose_name='Макс кол-во участников'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя матча'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_amateur_matches', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='participants',
            field=models.ManyToManyField(related_name='opponents_amateur_matches', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='requests',
            field=models.ManyToManyField(related_name='requests_amateur_matches', to=settings.AUTH_USER_MODEL, verbose_name='Запросы на участие'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='start',
            field=models.DateTimeField(verbose_name='Дата и время начала матча'),
        ),
    ]
