# Generated by Django 4.2.1 on 2024-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_amateurmatch_photo_amateurmatch_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amateurmatch',
            name='status',
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
