# Generated by Django 4.2.1 on 2024-04-02 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_amateurmatch_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='users',
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='city',
            field=models.TextField(default='', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='amateurmatch',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Описание матча'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='participants_tournament', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='requests_tournament', to=settings.AUTH_USER_MODEL, verbose_name='Запросы на участие'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.TextField(default='', verbose_name='Правила'),
        ),
    ]
