# Generated by Django 4.2.1 on 2024-04-02 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tournament_end_tournament_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournament_stage',
        ),
        migrations.RemoveField(
            model_name='matchparticipant',
            name='match',
        ),
        migrations.RemoveField(
            model_name='tournamentstage',
            name='tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(related_name='tournament_participants', to='main.matchparticipant', verbose_name='Участники турнира'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stages',
            field=models.ManyToManyField(related_name='stages', to='main.tournamentstage', verbose_name='Этапы турнира'),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание этапа'),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='matches',
            field=models.ManyToManyField(related_name='stage_matches', to='main.match', verbose_name='Матчи этапа турнира'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='main.matchparticipant', verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='requests',
            field=models.ManyToManyField(related_name='requests_tournament', to=settings.AUTH_USER_MODEL, verbose_name='Запросы на участие'),
        ),
        migrations.AlterField(
            model_name='tournamentstage',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало этапа'),
        ),
    ]
