# Generated by Django 4.2.1 on 2024-04-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tournament_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Счет')),
                ('result', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Победа'), (1, 'Поражение'), (2, 'Ничья')], null=True, verbose_name='Результат')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'verbose_name': 'Команда матча',
                'verbose_name_plural': 'Команды матчей',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='tournament_teams', to='main.matchteam', verbose_name='Команды турнира'),
        ),
    ]
