# Generated by Django 4.2.1 on 2024-04-05 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_confirmation_email_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Счет')),
                ('result', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Победа'), (1, 'Поражение'), (2, 'Ничья')], null=True, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Участник матча',
                'verbose_name_plural': 'Участники матчей',
            },
        ),
        migrations.RemoveField(
            model_name='matchparticipant',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teammemberrole',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='match',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Signle Elimination'), (1, 'Double Elimination'), (2, 'Round Robin'), (3, 'Swiss')], null=True, verbose_name='Тип сетки турнира'),
        ),
        migrations.DeleteModel(
            name='MatchTeam',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TeamMemberRole',
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(related_name='tournament_participants', to='main.participant', verbose_name='Участники турнира'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='main.participant', verbose_name='Победитель'),
        ),
        migrations.DeleteModel(
            name='MatchParticipant',
        ),
    ]
