# Generated by Django 4.2.1 on 2024-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_sport_icon_alter_sport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amateurmatch',
            name='photo',
        ),
        migrations.CreateModel(
            name='MatchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='amateur_matches_photos/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.amateurmatch')),
            ],
        ),
    ]
