# Generated by Django 4.2.1 on 2024-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_tournament_moderators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='duration',
        ),
        migrations.AddField(
            model_name='match',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время окончания'),
        ),
    ]
