# Generated by Django 4.2.1 on 2024-03-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amateurmatch',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sport', verbose_name='Вид спорта'),
            preserve_default=False,
        ),
    ]
