# Generated by Django 4.2.1 on 2024-04-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_match_tournament_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='max_participants_amount',
            new_name='max_participants',
        ),
    ]
