# Generated by Django 4.2.1 on 2024-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_max_participants_amount_tournament_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments_photos/'),
        ),
    ]
