# Generated by Django 4.2.1 on 2024-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_match_scheduled_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='amateurmatch',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержден модерацией'),
        ),
    ]
