# Generated by Django 4.2.1 on 2024-04-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_amateurmatch_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_lose_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_match_on_lose', to='main.match', verbose_name='Следующий матч при поражении'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_match_on_win', to='main.match', verbose_name='Следующий матч'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждено модератором'),
        ),
    ]
