# Generated by Django 4.2.1 on 2024-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_match_next_lose_match_match_next_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='sports_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.FileField(upload_to='sports_images/', verbose_name='Изображение'),
        ),
    ]
