# Generated by Django 4.2.1 on 2024-04-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_matchphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='auto_accept_participants',
            field=models.BooleanField(default=False, verbose_name='Автоматически принимать всех'),
        ),
    ]
