# Generated by Django 4.2.1 on 2024-04-17 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_tournament_auto_accept_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='moderators',
            field=models.ManyToManyField(related_name='moderators_tournament', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы турнира'),
        ),
    ]
