# Generated by Django 4.2.1 on 2024-04-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_participant_result_remove_participant_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='place',
        ),
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.TextField(default='', verbose_name='Город'),
        ),
    ]
