# Generated by Django 4.2.1 on 2024-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_tournament_place_tournament_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allow_not_full_teams',
            field=models.BooleanField(default=False, verbose_name='Разрешить участвовать командам с неполными составами'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Очки за ничью'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_team_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество участников в команде'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_team_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество участников в команде'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во туров'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='win_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Очки за победу'),
        ),
    ]
