# Generated by Django 4.2.1 on 2024-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_tournament_allow_not_full_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Общий счет'),
        ),
    ]
