# Generated by Django 4.2.1 on 2024-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_participant_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='min_team_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество участников в команде'),
        ),
    ]
