# Generated by Django 4.2.1 on 2024-04-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_tournament_min_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='check_score_difference_on_draw',
            field=models.BooleanField(default=False, verbose_name='Если очки равны. Первым смотреть разницу в очках'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mathces_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество игр с каждым игроком'),
        ),
    ]
