# Generated by Django 4.2.1 on 2024-04-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_tournament_check_score_difference_on_draw_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentPlace',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='tournamentstage',
            name='matches',
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match_stage', to='main.tournamentstage', verbose_name='Этап матча'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participant_tournament', to='main.tournament', verbose_name='Учатник турнира'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stage_tournament', to='main.tournament', verbose_name='Турнир этапа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='address',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='city',
            field=models.TextField(db_index=True, default='', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='enter_price',
            field=models.IntegerField(db_index=True, verbose_name='Цена входа'),
        ),
        migrations.AlterField(
            model_name='amateurmatch',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Имя матча'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время окончания регистрации'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='enter_price',
            field=models.IntegerField(db_index=True, verbose_name='Цена участия'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время начала регистрации'),
        ),
    ]
