# Generated by Django 4.2.1 on 2024-04-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_delete_tournamentplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.tournamentstage', verbose_name='Этап матча'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.tournament', verbose_name='Учатник турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bracket',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Signle Elimination'), (1, 'Double Elimination'), (2, 'Round Robin'), (3, 'Swiss'), (4, 'Leaderboard')], null=True, verbose_name='Тип сетки турнира'),
        ),
        migrations.AlterField(
            model_name='tournamentstage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='main.tournament', verbose_name='Турнир этапа'),
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='main.participant', verbose_name='Участник')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.tournamentstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Результат этапа',
                'verbose_name_plural': 'Результаты этапов',
            },
        ),
    ]
