# Generated by Django 4.2.1 on 2024-04-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_match_stage_alter_participant_tournament_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchphoto',
            options={'verbose_name': 'Фото матча', 'verbose_name_plural': 'Фото матча'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Одноступенчатый'), (1, 'Двуступенчатый')], null=True, verbose_name='Тип турнира'),
        ),
    ]
