# Generated by Django 4.2.1 on 2024-04-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_matchphoto_options_tournament_tournament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='photo',
        ),
        migrations.CreateModel(
            name='TournamentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='tournament_photos/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.tournament')),
            ],
            options={
                'verbose_name': 'Фото турнира',
                'verbose_name_plural': 'Фото турниров',
            },
        ),
    ]
