# Generated by Django 4.2.1 on 2024-04-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_tournament_photo_tournamentphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentphoto',
            old_name='match',
            new_name='tournament',
        ),
    ]
