# Generated by Django 4.2.1 on 2024-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_match_tournamentphoto_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active_stage_position',
            field=models.IntegerField(default=1, verbose_name='Позиция активного этапа'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='final_stage_advance_count',
            field=models.IntegerField(default=2, verbose_name='Количество команд которые проходят в плей-офф'),
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Позиция этапа (какой он идёт по счету)'),
        ),
    ]
