# Generated by Django 4.2.1 on 2024-04-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_tournament_active_stage_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='place',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место в турнире'),
        ),
    ]
