# Generated by Django 4.2.1 on 2024-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_participant_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants_in_group',
            field=models.IntegerField(default=2, verbose_name='Количество участников в группе'),
        ),
    ]
