# Generated by Django 4.2.1 on 2024-04-29 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_tournament_register_open_until_alter_tournament_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='register_open_until',
            field=models.CharField(choices=[('15 мин', datetime.timedelta(seconds=900)), ('30 мин', datetime.timedelta(seconds=1800)), ('1 час', datetime.timedelta(seconds=3600)), ('2 часа', datetime.timedelta(seconds=7200)), ('6 часов', datetime.timedelta(seconds=21600)), ('1 день', datetime.timedelta(days=1)), ('2 дня', datetime.timedelta(days=2))], default='15 мин', max_length=50, verbose_name='Регистрация открыта до...'),
        ),
    ]
