# Generated by Django 4.2.1 on 2024-04-29 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_tournament_register_open_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(128)], verbose_name='Максимальное количество участников'),
        ),
    ]
