# Generated by Django 4.2.1 on 2024-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_tournament_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='address',
            field=models.TextField(default='', verbose_name='Адрес'),
        ),
    ]
