# Generated by Django 4.2.1 on 2024-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_tournament_first_place_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='group_stage_draw_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Очки за ничью (Групповой этап)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_stage_rounds_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во туров (Групповой этап)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_stage_win_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Очки за победу (Групповой этап)'),
        ),
    ]
