# Generated by Django 4.2.1 on 2024-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_tournament_group_stage_draw_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='BO_number',
            field=models.IntegerField(default=1, verbose_name='В игре провожится BO_number матчей'),
        ),
    ]
