# Generated by Django 4.2.1 on 2024-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_tournament_bo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='group_stage_BO_number',
            field=models.IntegerField(default=1, verbose_name='Количество встреч в матче (Групповой этап)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='BO_number',
            field=models.IntegerField(default=1, verbose_name='Количество встреч в матче'),
        ),
    ]
