# Generated by Django 4.2.1 on 2024-04-29 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_tournament_group_stage_bo_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='BO_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество встреч в матче'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='enter_price',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Цена участия'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='final_stage_advance_count',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)], verbose_name='Количество команд которые проходят в плей-офф'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='first_place_prize',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Награда за 1 место'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='group_stage_BO_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество встреч в матче (Групповой этап)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='group_stage_rounds_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Кол-во туров (Групповой этап)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mathces_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество игр с каждым игроком'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_team_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальное количество участников в команде'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_team_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальное количество участников в команде'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants_in_group',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(64)], verbose_name='Количество участников в группе'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Кол-во туров'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='second_place_prize',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Награда за 2 место'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='third_place_prize',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Награда за 3 место'),
        ),
    ]
