# Generated by Django 4.2.1 on 2024-04-29 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_tournament_bo_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Призовой фонд'),
        ),
    ]
