# Generated by Django 4.2.1 on 2024-04-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_tournament_prize_pool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник турнира', 'verbose_name_plural': 'Участники турнира'},
        ),
    ]
