# Generated by Django 4.2.1 on 2024-05-02 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_participant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='final_BO_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество встреч в финале'),
        ),
    ]
