# Generated by Django 4.2.1 on 2024-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_tournament_final_bo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='final_step_score',
            field=models.FloatField(default=0.0, verbose_name='Общий счет в финальной группе'),
        ),
    ]
