# Generated by Django 4.2.1 on 2024-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_participant_final_step_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstage',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Завершен ли этап'),
        ),
    ]
