# Generated by Django 4.2.1 on 2024-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_tournamentstage_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qualified',
            field=models.BooleanField(default=False, verbose_name='Вышел ли из групповой стадии'),
        ),
    ]
